# version format
version: uwx-nightly-{build}

# Build worker image (VM template)
image: Visual Studio 2017

clone_folder: c:\projects\dsp

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/uwx/MadSharp.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

branches:
  only:
    - master

environment:
  access_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ

install:
  - cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

before_build:
  - cmd: nuget restore

build: off

build_script:
  - ps: dotnet build "MadGame.sln" -c Debug
  - ps: dotnet publish "MadGame.sln" --configuration Debug -f net47

after_build:
  - cmd: 7z a MadSharp.zip %APPVEYOR_BUILD_FOLDER%\\MadSharp\\bin\\Debug\\net47\\publish\\*
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\\MadSharp
  - cmd: 7z a ..\MadSharp.zip GameData
  
artifacts:
  - path: "MadSharp.zip"
    name: Release (.NET 4.7)
    type: zip

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds

deploy:
  release: madsharp-v$(appveyor_build_version)
  description: 'MadSharp rev $(APPVEYOR_BUILD_NUMBER)'
  provider: GitHub
  auth_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ # your encrypted token from GitHub
  artifact: /.*/            # upload everything to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false       # deploy on tag push only

notifications:
  - provider: Slack
    on_build_success: true
    on_build_failure: true
    incoming_webhook:
      secure: +5y63VhkKwOZVK264xwgH8gp7vI2cJivXvseQeSoYYNyH3wjOtid8Qz+gyNOjCGpI/xqxxJNwqFrL75ZPHYOYEKs9WhBWznTsFpJUAs5hxn1kcczMv6WYuwUzXJNEdqX6m47PnS7xrzUZJIRWNQCHRJCtN5VX+hXfVV6BT+tKQdRDeRr/LANhRLr2pAbIOGP
